services:
  - name: SendSmsToMobileNumber
    type: web
    runtime: docker
    repo: https://github.com/nycanshu/SendSmsToMobileNumber
    plan: free  # Change to 'starter' or 'pro' if needed
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false  # Set to true if stored in GitHub secrets
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
    dockerfilePath: ./Dockerfile
    env: docker
    autoDeploy: true  # Enable auto-deployment on new commits
    healthCheckPath: /
    region: oregon  # Change region if needed
